//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int StudentID { get; set; }
        public int ClassSchduleID { get; set; }
        public System.DateTime ClassDate { get; set; }
        public string Status { get; set; }
    
        public virtual Class_Schedule Class_Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
