//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Tbl
    {
        public Class_Tbl()
        {
            this.Class_Schedule = new HashSet<Class_Schedule>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Class_Schedule> Class_Schedule { get; set; }
    }
}
