//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Class_Schedule = new HashSet<Class_Schedule>();
        }
    
        public int TeacherID { get; set; }
        public string FIrstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public System.DateTime Hired_Date { get; set; }
        public Nullable<int> PhoneNo { get; set; }
    
        public virtual ICollection<Class_Schedule> Class_Schedule { get; set; }
    }
}
